
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Statement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 2
 */
public class admin extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    public admin() {
        initComponents();
        try {
            System.out.println("connection and updating database");
            System.out.println("Using JDBC + Oracle on java");
            Class.forName("oracle.jdbc.OracleDriver").newInstance();
            conn = Connector.ConnectDb();
            System.out.println("Connection made");
            //conn = DriverManager.getConnection("jdbc:oracle:thin:@10.0.18.2:1521:orcl","mok04824", "mok04824");              
        } 
        catch (Exception E) {
            System.err.println("Unable to load driver.");
            E.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        sid = new javax.swing.JTextField();
        addStudent = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        informationTable = new javax.swing.JTable();
        viewAllStudents = new javax.swing.JButton();
        searchByID = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        Day = new javax.swing.JSpinner();
        Month = new javax.swing.JSpinner();
        Year = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Adding a Student");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1000, 40));
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 150, -1));

        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });
        getContentPane().add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 150, -1));
        getContentPane().add(sid, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 120, -1));

        addStudent.setText("Add");
        addStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentActionPerformed(evt);
            }
        });
        getContentPane().add(addStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 90, -1));

        informationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "First Name", "Last Name", "Age", "Student Type"
            }
        ));
        jScrollPane1.setViewportView(informationTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 710, 140));

        viewAllStudents.setText("View");
        viewAllStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAllStudentsActionPerformed(evt);
            }
        });
        getContentPane().add(viewAllStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 490, -1, -1));

        searchByID.setText("Search");
        searchByID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByIDActionPerformed(evt);
            }
        });
        getContentPane().add(searchByID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 550, -1));

        jLabel3.setText("Student ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, 20));

        jLabel4.setText("Age");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, -1, -1));

        jLabel5.setText("Last Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 80, 20));

        jLabel6.setText("First Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 70, 20));

        jLabel7.setText("Student Type");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        jButton1.setText("update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 490, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Undergraduate", "Postgraduate" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 120, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Student Administration ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1000, 60));

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(18, 0, 100, 1));
        getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, 60, -1));

        jLabel8.setText("Date of Birth");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, -1, -1));

        Day.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        Day.setToolTipText("Day");
        getContentPane().add(Day, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 70, -1));

        Month.setModel(new javax.swing.SpinnerListModel(new String[] {"01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"}));
        Month.setToolTipText("Month");
        getContentPane().add(Month, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, 70, -1));

        Year.setModel(new javax.swing.SpinnerNumberModel(2000, 1950, 3000, 1));
        Year.setToolTipText("Year");
        getContentPane().add(Year, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 140, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentActionPerformed
      try {
          //Uliyan, formatting date to MySQL date format
          String date = Year.getValue().toString() + "-" + Month.getValue().toString() + "-";          
          if(Day.getValue().toString().length() == 1){
              date += "0" + Day.getValue().toString();
          }else{
              date += Day.getValue().toString();
          }
          
          //Uliyan, ensuring student id is of length 8
          String studentId = sid.getText();
          if(studentId.length() != 8){
              JOptionPane.showMessageDialog(null, "Student ID should be of length 8");
              return;
          }         
          
          String sql = "INSERT INTO student(S_ID,DoB,Fname,Lname,Age, Program) VALUES(?,?,?,?,?,?)";
          pst = conn.prepareStatement(sql);
          pst.setInt(1,Integer.parseInt(sid.getText()));
          pst.setString(2,date);
          pst.setString(3,fname.getText());
          pst.setString(4,lname.getText());
          pst.setString(5,jSpinner1.getValue().toString());
          pst.setString(6,jComboBox1.getSelectedItem().toString());
          pst.executeUpdate();
          JOptionPane.showMessageDialog(null, "Inserted successfully!!");
      } catch (SQLException ex) {
            Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
            
        }
    }//GEN-LAST:event_addStudentActionPerformed

    private void searchByIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByIDActionPerformed
        // TODO add your handling code here:
           try {
            // TODO add your handling code here:
            DefaultTableModel tableModel = (DefaultTableModel) informationTable.getModel();
            //String searchName = lname.getText();
            int SearchID = Integer.parseInt(sid.getText());
            PreparedStatement search = conn.prepareStatement("SELECT * FROM STUDENT WHERE STUDENTID = ?");
            search.setInt(1, SearchID);
            ResultSet rs = search.executeQuery();
            
            while(rs.next()){
                int id = rs.getInt("STUDENTID");
                String fName = rs.getString("FIRSTNAME");
                String lName = rs.getString("LASTNAME");
                int age = rs.getInt("AGE");
                String type = rs.getString("STUDENTTYPE");             
                tableModel.addRow(new Object[]{id, fName,lName, age,type });
            }
            search.close();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_searchByIDActionPerformed

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed

    private void viewAllStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAllStudentsActionPerformed
        // TODO add your handling code here:

              try {
            // TODO add your handling code here:
            DefaultTableModel tableModel = (DefaultTableModel) informationTable.getModel();
            String s = "SELECT * FROM STUDENT";
            Statement stmt = conn.createStatement();
            rs = stmt.executeQuery(s);
            
            while(rs.next()){
                int id = rs.getInt("STUDENTID");
                String fName = rs.getString("FIRSTNAME");
                String lName = rs.getString("LASTNAME");
                int age = rs.getInt("AGE");
                String type = rs.getString("STUDENTTYPE");             
                tableModel.addRow(new Object[]{id, fName,lName, age,type });
            }
            rs.close();
            
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_viewAllStudentsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
                String sql = "Update STUDENT "
                        + "set LASTNAME = ?"
                        + "  where STUDENTID=?";

                pst=conn.prepareStatement(sql);
                  pst.setString(1, lname.getText());
                pst.setInt(2, Integer.parseInt(sid.getText()));
              

                rs=pst.executeQuery();
                            }
                    catch (SQLException e) 
                    {
                    JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner Day;
    private javax.swing.JSpinner Month;
    private javax.swing.JSpinner Year;
    private javax.swing.JButton addStudent;
    private javax.swing.JTextField fname;
    private javax.swing.JTable informationTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField lname;
    private javax.swing.JButton searchByID;
    private javax.swing.JTextField sid;
    private javax.swing.JButton viewAllStudents;
    // End of variables declaration//GEN-END:variables
}
