/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Statement;
import java.util.Calendar;

/**
 *
 * @author 201603004
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public Registration() {
        initComponents();
        try {
            System.out.println("Example 1");
            System.out.println("Using JDBC + Oracle on java");
            // DriverManager.registerDriver (new oracle.jdbc.OracleDriver());
            Class.forName("oracle.jdbc.OracleDriver").newInstance();
            conn = DriverManager.getConnection("jdbc:oracle:thin:@10.0.18.2:1521:orcl",
                "mat01055", "mat01055");
        } 
        catch (Exception E) {
            System.err.println("Unable to load driver.");
            E.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        sid = new javax.swing.JTextField();
        ccode = new javax.swing.JTextField();
        regForCourse = new javax.swing.JButton();
        viewRegByYear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("COURSE REGISTRATION ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 980, 30));
        getContentPane().add(sid, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 90, -1));
        getContentPane().add(ccode, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 110, -1));

        regForCourse.setText("REGISTER FOR COURSE");
        regForCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regForCourseActionPerformed(evt);
            }
        });
        getContentPane().add(regForCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, -1));

        viewRegByYear.setText("VIEW COURSE REGISTRATIONS AND MODULES BY YEAR");
        viewRegByYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRegByYearActionPerformed(evt);
            }
        });
        getContentPane().add(viewRegByYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 380, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Course Code", "Date Of Registration"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 690, 160));

        jLabel3.setText("Student ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel4.setText("Course Code");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regForCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regForCourseActionPerformed
       
            try {
          String sql = "INSERT INTO COURSEREGISTRATION(STUDENTID,COURSECODE) VALUES(?,?)";
          pst = conn.prepareStatement(sql);
          pst.setInt(1,Integer.parseInt(sid.getText()));
          pst.setString(2,ccode.getText());
          pst.executeUpdate();
          JOptionPane.showMessageDialog(null, "Inserted!!");
      } catch (SQLException ex) {
            Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
            
        }
        
    }//GEN-LAST:event_regForCourseActionPerformed

    private void viewRegByYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRegByYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewRegByYearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ccode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton regForCourse;
    private javax.swing.JTextField sid;
    private javax.swing.JButton viewRegByYear;
    // End of variables declaration//GEN-END:variables
}
